export const computers = [
  {
    price: 1299,
    manufacturer: "Apple",
    model: "MacBook Air",
    features: ["M1 chip", "13.3-inch Retina display", "8GB RAM", "256GB SSD"],
    pictures: [
      "https://example.com/macbook-air-1.jpg",
      "https://example.com/macbook-air-2.jpg",
    ],
    appleProduct: true,
  },
  {
    price: 1999,
    manufacturer: "Apple",
    model: "MacBook Pro 14",
    features: [
      "M1 Pro chip",
      "14.2-inch Liquid Retina XDR display",
      "16GB RAM",
      "512GB SSD",
    ],
    pictures: [
      "https://example.com/macbook-pro-14-1.jpg",
      "https://example.com/macbook-pro-14-2.jpg",
    ],
    appleProduct: true,
  },
  // {
  //   price: 2499,
  //   manufacturer: "Apple",
  //   model: "MacBook Pro 16",
  //   features: [
  //     "M1 Max chip",
  //     "16.2-inch Liquid Retina XDR display",
  //     "32GB RAM",
  //     "1TB SSD",
  //   ],
  //   pictures: [
  //     "https://example.com/macbook-pro-16-1.jpg",
  //     "https://example.com/macbook-pro-16-2.jpg",
  //   ],
  //   appleProduct: true,
  // },
  // {
  //   price: 1799,
  //   manufacturer: "Apple",
  //   model: "iMac 24",
  //   features: [
  //     "M1 chip",
  //     "24-inch 4.5K Retina display",
  //     "8GB RAM",
  //     "256GB SSD",
  //   ],
  //   pictures: [
  //     "https://example.com/imac-24-1.jpg",
  //     "https://example.com/imac-24-2.jpg",
  //   ],
  //   appleProduct: true,
  // },
  // {
  //   price: 2999,
  //   manufacturer: "Apple",
  //   model: "iMac 27",
  //   features: [
  //     "Intel Core i9",
  //     "27-inch 5K Retina display",
  //     "16GB RAM",
  //     "512GB SSD",
  //   ],
  //   pictures: [
  //     "https://example.com/imac-27-1.jpg",
  //     "https://example.com/imac-27-2.jpg",
  //   ],
  //   appleProduct: true,
  // },
  {
    price: 1099,
    manufacturer: "Dell",
    model: "XPS 13",
    features: [
      "Intel Core i7",
      "13.4-inch FHD display",
      "16GB RAM",
      "512GB SSD",
    ],
    pictures: [
      "https://example.com/dell-xps-13-1.jpg",
      "https://example.com/dell-xps-13-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 1299,
    manufacturer: "Dell",
    model: "XPS 15",
    features: [
      "Intel Core i7",
      "15.6-inch UHD+ display",
      "16GB RAM",
      "1TB SSD",
    ],
    pictures: [
      "https://example.com/dell-xps-15-1.jpg",
      "https://example.com/dell-xps-15-2.jpg",
    ],
    appleProduct: false,
  },
  // {
  //   price: 1999,
  //   manufacturer: "Dell",
  //   model: "XPS 17",
  //   features: ["Intel Core i9", "17-inch UHD+ display", "32GB RAM", "1TB SSD"],
  //   pictures: [
  //     "https://example.com/dell-xps-17-1.jpg",
  //     "https://example.com/dell-xps-17-2.jpg",
  //   ],
  //   appleProduct: false,
  // },
  {
    price: 1399,
    manufacturer: "HP",
    model: "Spectre x360 14",
    features: [
      "Intel Core i7",
      "13.5-inch FHD touch display",
      "16GB RAM",
      "512GB SSD",
    ],
    pictures: [
      "https://example.com/hp-spectre-14-1.jpg",
      "https://example.com/hp-spectre-14-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 1699,
    manufacturer: "HP",
    model: "Spectre x360 15",
    features: [
      "Intel Core i7",
      "15.6-inch 4K touch display",
      "16GB RAM",
      "1TB SSD",
    ],
    pictures: [
      "https://example.com/hp-spectre-15-1.jpg",
      "https://example.com/hp-spectre-15-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 1499,
    manufacturer: "Asus",
    model: "ZenBook 14",
    features: ["AMD Ryzen 9", "14-inch FHD display", "16GB RAM", "1TB SSD"],
    pictures: [
      "https://example.com/asus-zenbook-14-1.jpg",
      "https://example.com/asus-zenbook-14-2.jpg",
    ],
    appleProduct: false,
  },
  // {
  //   price: 1799,
  //   manufacturer: "Asus",
  //   model: "ZenBook Pro Duo",
  //   features: [
  //     "Intel Core i9",
  //     "15.6-inch 4K OLED display",
  //     "32GB RAM",
  //     "1TB SSD",
  //   ],
  //   pictures: [
  //     "https://example.com/asus-zenbook-pro-duo-1.jpg",
  //     "https://example.com/asus-zenbook-pro-duo-2.jpg",
  //   ],
  //   appleProduct: false,
  // },
  {
    price: 999,
    manufacturer: "Lenovo",
    model: "ThinkPad X1 Carbon",
    features: ["Intel Core i7", "14-inch FHD display", "16GB RAM", "512GB SSD"],
    pictures: [
      "https://example.com/lenovo-thinkpad-x1-1.jpg",
      "https://example.com/lenovo-thinkpad-x1-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 1199,
    manufacturer: "Lenovo",
    model: "Yoga 9i",
    features: [
      "Intel Core i7",
      "14-inch 4K touch display",
      "16GB RAM",
      "512GB SSD",
    ],
    pictures: [
      "https://example.com/lenovo-yoga-9i-1.jpg",
      "https://example.com/lenovo-yoga-9i-2.jpg",
    ],
    appleProduct: false,
  },
  // {
  //   price: 1499,
  //   manufacturer: "Microsoft",
  //   model: "Surface Laptop 4",
  //   features: [
  //     "AMD Ryzen 7",
  //     "13.5-inch PixelSense display",
  //     "16GB RAM",
  //     "512GB SSD",
  //   ],
  //   pictures: [
  //     "https://example.com/surface-laptop-4-1.jpg",
  //     "https://example.com/surface-laptop-4-2.jpg",
  //   ],
  //   appleProduct: false,
  // },
  {
    price: 1799,
    manufacturer: "Microsoft",
    model: "Surface Book 3",
    features: [
      "Intel Core i7",
      "15-inch PixelSense display",
      "32GB RAM",
      "1TB SSD",
    ],
    pictures: [
      "https://example.com/surface-book-3-1.jpg",
      "https://example.com/surface-book-3-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 899,
    manufacturer: "Acer",
    model: "Swift 3",
    features: ["AMD Ryzen 7", "14-inch FHD display", "8GB RAM", "512GB SSD"],
    pictures: [
      "https://example.com/acer-swift-3-1.jpg",
      "https://example.com/acer-swift-3-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 1299,
    manufacturer: "Acer",
    model: "Spin 5",
    features: [
      "Intel Core i7",
      "13.5-inch 2K touch display",
      "16GB RAM",
      "512GB SSD",
    ],
    pictures: [
      "https://example.com/acer-spin-5-1.jpg",
      "https://example.com/acer-spin-5-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 1099,
    manufacturer: "Razer",
    model: "Blade Stealth 13",
    features: [
      "Intel Core i7",
      "13.3-inch FHD display",
      "16GB RAM",
      "512GB SSD",
    ],
    pictures: [
      "https://example.com/razer-blade-stealth-13-1.jpg",
      "https://example.com/razer-blade-stealth-13-2.jpg",
    ],
    appleProduct: false,
  },
  {
    price: 2999,
    manufacturer: "Razer",
    model: "Blade 15",
    features: [
      "Intel Core i9",
      "15.6-inch 4K OLED display",
      "32GB RAM",
      "1TB SSD",
    ],
    pictures: [
      "https://example.com/razer-blade-15-1.jpg",
      "https://example.com/razer-blade-15-2.jpg",
    ],
    appleProduct: false,
  },
];
